### ISSUE TITLE
Current solution breaks the original SuperCollider.app

### ISSUE THREAD

**Issue by rukano** [dathinaios/spacemacs-supercollider#2]
The current solution is to link the `sc` folder directly to the app support directoy, but this is a little bit destructive, since the normal SuperCollider.app won't compile (Duplicated Document.sc) class. I know there is this `'(sclang-library-configuration-file "path_to/emacs_cfg.yaml")` which I set in the custon-set-variables (in my old emacs system, not spacemacs)... But this doesn't seem to be working. In the config file is something like:

```yaml
includePaths:
    - /Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary
    - /Library/Application Support/SuperCollider/Extensions
    - /Users/username/.emacs.d/private/supercollider/sc
excludePaths:
    []
postInlineWarnings: false
```

So the sclang started from emacs will compile these paths (including the emacs classes), and the normal SuperCollider.app won't notice anything... Do you have any idea why setting the path to library configuration file is not working? I've tried doing it in several places... in `.spacemacs`, in `packages.el`... no success... Only succeeded with your version, linking the `sc` folder directly to the extensions...
